### ISSUE TITLE
Status 500: update-service fails out of the box

### ISSUE THREAD

**Issue by RobertWalter83** [eclipse/xtext-web#2] opened 2016-06-20 13:40 UTC
Hi,

I work with Xtext 2.10.0.v201605250459.
I've created a new Xtext project using the wizard, just creating the "web" project and the required projects for that. I use Gradle for the built.

After I've created the Xtext artifacts and ran the built, I start the server and find the "Example Web Editor" at localhost:8080. I use all the defaults that come from the wizard.

Now I get a bunch of 500s from the server:
![web500](https://cloud.githubusercontent.com/assets/5462981/16195977/3f8053b8-36fc-11e6-9dbc-885873a361ae.png)

Looking at my sources, the URL used to PUT/GET stuff doesn't exist, but I'm admittedly new to web development, so I can only tell you what I observe.

Am I missing something?

**Comment by cdietrich** [comment] 2016-09-06 09:25
@RobertWalter83 does this happen if you use the workaround mentioned in https://github.com/eclipse/xtext-web/issues/5 as well?

**Comment by cdietrich** [comment] 2016-09-23 16:05
as getting no feedback from @RobertWalter83  i will close this as duplicate of #5

**Closed by cdietrich** 2016-09-23 16:05 UTC
